name: Notify Discord on Push

on:
  push:
    branches:
      - master  # o la rama que quieras

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🚀 Nuevo push en **${GITHUB_REPOSITORY}** por **${GITHUB_ACTOR}**\n🔗 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
